### ISSUE TITLE
[Bug]: Call to a member function filter() on null 

### ISSUE THREAD

**Issue by SergioMendolia** [kiwilan/php-ebook#38]
### What happened?

Hello!

First of all, thanks for this great library! 

I'm having an issue when an archive is a "badFile". Currently, the error is caught in `Ebook.php`, but it is only logged and the script continues. 
Later on, the `*Metadata.php` files, use the `getArchive()->xx` method, and since the archive is null, the error is thrown. Since it's an error and not an Exception, the execution stops.

I can provide a PR for this, I would just like your preferred method of fixing it.
- I can throw an Error on the `getArchive()` and typhint it as not nullable but I don't have enough visibility on the rest of the code to see if it's a good solution.
- I could add a new `Epub::check($path)` to check a file before trying to read it
- Any other idea?

Thanks!

### How to reproduce the bug

Try to read a bad archive :)

### Package Version

2.0.12

### PHP Version

8.2

### Which operating systems does with happen with?

Linux

**Comment by ewilan-riviere** [comment]
Thanks for this report!

It's a very good idea!

### ePUB check

It's possible to check ePUB with method `isBadFile()` after reading.

```php
$ebook = Ebook::read(EPUB_BAD_FILE);

if ($ebook->isBadFile()) {
    continue
}
```

But it could be a good idea to add a static method to pre-check file!

### Archive

Do you want an exception directly in `getArchive`?

```php
public function getArchive(): ?BaseArchive
{
    if (! $this->archive) {
        throw new \Exception("{$this->path} can't be read as archive.");
    }

    return $this->archive;
}
```

**Comment by SergioMendolia** [comment]
`Ebook::isValid` fixed my issue! Great, thanks for the quick response!

**Comment by ewilan-riviere** [comment]
Thanks for your contributions!

Everything works now on your side?

**Comment by SergioMendolia** [comment]
👌🏽 Everything looks great thank you!
